version: "3.0"
services:
  nodered: 
    build: ./nodered
    image: localbuild/nodered:latest
    container_name: nodered
    restart: unless-stopped
    ports: 
      - "1880:1880"
    volumes:
      - noderedData:/data
    networks:
      - edge
  grafana:
    build: ./grafana
    image: localbuild/grafana/grafana:9.5.1
    container_name: grafana
    restart: unless-stopped #always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_SKIP_VERITY=true
      - GF_SMTP_HOST=vps-6efa1560.vps.ovh.net:25  
      - GF_SMTP_USER=admin@vps-6efa1560.vps.ovh.net
      - GF_SMTP_PASSWORD=admin
      - GF_SERVER_DOMAIN=grafana.server.name
      - GF_SERVER_ROOT_URL=http://grafana.server.name
      - GF_SERVER_PORT=80


      - GF_SMTP_FROM_ADDRESS=admin@localhost:25
    ports:
      - "3000:3000"
    volumes: 
      - grafanaData:/var/lib/grafana
    networks:
      - edge
  influxdb:
    build: ./influx
    image: localbuild/influxdb:2.7.1
    container_name: influxdb
    restart: unless-stopped
    environment:
      INFLUXDB_DB: HAPE
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: user
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    volumes:
      - influxData:/var/lib/influxdb
    networks: 
      - edge
  mosquitto:
    build: ./mosquitto
    image: localbuild/mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports: 
      - "8883:8883"  #1883
      - "9001:9001"
    volumes: 
      - mosquittoLog:/mosquitto/log
      - mosquittoData:/mosquitto/data
    networks:
      - edge
#Create internal link network for Containers
networks:
  edge:

#Create Volumes for persistent Storage
volumes:
  grafanaData:
  noderedData:
  influxData:
  mosquittoLog:
  mosquittoData: