version: "3.0"
services:
  nodered: 
    build: ./nodered
    image: localbuild/nodered:latest
    container_name: nodered
    restart: always #unless-stopped
    ports: 
      - "1880:1880"
    volumes:
      - noderedData:/data
    networks:
      - edge
  grafana:
    build: ./grafana
    image: localbuild/grafana/grafana:latest
    container_name: grafana
    restart: always #unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER = admin
      - GF_SECURITY_ADMIN_PASSWORD = admin
      - GF_INSTALL_PLUGINS=
    ports:
      - "3000:3000"
    volumes: 
      - grafanaData:/var/lib/grafana
    networks:
      - edge
  influxdb:
    build: ./influx
    image: localbuild/influxdb:2.6
    container_name: influxdb
    restart: always #unless-stopped
    environment:
      INFLUXDB_DB: HAPE
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: user
    ports:
      - "8082:8082"
      - "8086:8086"
      - "8089:8089"
    volumes:
      - influxData:/var/lib/influxdb
    networks: 
      - edge
  mosquitto:
    build: ./mosquitto
    image: localbuild/mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports: 
      - "8883:8883"  #1883
      - "9001:9001"
    volumes: 
      - mosquittoLog:/mosquitto/log
      - mosquittoData:/mosquitto/data
    networks:
      - edge
#Create internal link network for Containers
networks:
  edge:

#Create Volumes for persistent Storage
volumes:
  grafanaData:
  noderedData:
  influxData:
  mosquittoLog:
  mosquittoData: