{
 "title": "andrej_no1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HP-012",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reg0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"lat\")"
    }
   ]
  },
  { "title": "status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Unit Status (reg 0)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reg0\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"lat\")"
    }
   ]
  },
  {
   "title": "Unit Mode (Reg 1)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reg1\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"lat\")"
    }
   ]
  },
  {
   "title": "Tout(T1), Tair(back-T4), Tcwu (back-T6)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"T1_Out\" or r[\"_field\"] == \"T4_AirReturn\" or r[\"_field\"] == \"T6_EconIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "temperatures chart T2, T3, T4, T5, T6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Sensors (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"T1_Out\" or r[\"_field\"] == \"T6_EconIn\" or r[\"_field\"] == \"T2_CoilOut\" or r[\"_field\"] == \"T3_HeatExch\" or r[\"_field\"] == \"T4_AirReturn\" or r[\"_field\"] == \"T5_AirExt\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "power ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Power (W)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "  from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acv\" or r[\"_field\"] == \"acc\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: r.acv * r.acc }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Current (A)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc\" or r[\"_field\"] == \"compc\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "inlet and load status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Inlet / Outlet water (Reg 2)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reg2\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"lat\")"
    }
   ]
  },
  {
   "title": "Load Status 1 (reg 3)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reg3\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"lat\")"
    }
   ]
  },
  {
   "title": "Load Status 2 (Reg 4)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reg4\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "auto - temperatures: c.o. | c.w.u",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "Tryb Auto - Temperatura Grzania , Temperatura c.w.u.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"auto_temp_co\" or r[\"_field\"] == \"auto_temp_cwu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "auto - timers: c.o. | c.w.u ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Tryb Auto - Timers [min] c.o. | c.w.u.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_co\" or r[\"_field\"] == \"time_cwu\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "manual - temperatures: c.o. | c.w.u | cooling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "manual mode - c.o. | c.w.u. | cooling",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"manual_temp_co\" or r[\"_field\"] == \"manual_temp_cwu\" or r[\"_field\"] == \"temp_frzn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "sensors(1):  T1 - out | T2 - coil out",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sensors(1): T1 (Out)  T2 (Coi Out)",
     "type": "gauge",
     "description": "sensory temperatury w pompie",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"T1_Out\" or r[\"_field\"] == \"T2_CoilOut\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"start\")"
      }
     ]
    }
   ]
  },
  {
   "title": "sensors(2):    T3 - heat exch. | T4 - air return",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sensors(2): T3 (Heat Exch.)  T4 (Air Return)",
     "type": "gauge",
     "description": "sensory temperatury w pompie",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"T3_HeatExch\" or r[\"_field\"] == \"T4_AirReturn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "sensors(3):    T5 - air exch. | T6 - econ in",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sensors(3): T5 (Air Exch.)  T6 (Econ In)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"T5_AirExt\" or r[\"_field\"] == \"T6_EconIn\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  { "title": "electro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Inout Voltage - Vin(ac) (V)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acv\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Input Current - I(ac) (A)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Compressor c. - Icc(ac) (A)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"compc\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "pressures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "lpres",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lpres\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "hpres",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hpres\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "eev",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"eev\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "evi",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"evi\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "warm curve settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Nastawy Krzywej Grzewczej",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Hi_Ta\" or r[\"_field\"] == \"Hi_Ts\" or r[\"_field\"] == \"Lo_Ta\" or r[\"_field\"] == \"Lo_Ts\" or r[\"_field\"] == \"wspK\" or r[\"_field\"] == \"offset\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error 1 (reg 31)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 16, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Err1\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Error 2 (reg 32)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 16, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Err2\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"lat\")"
      }
     ]
    },
    {
     "title": "Error 3 (reg 33)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 16, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Err3\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"lat\")"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Err1\" or r[\"_field\"] == \"Err2\" or r[\"_field\"] == \"Err3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  { "title": "heat pump - version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"hape\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"andr_n00001\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"version\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"lat\")"
    }
   ]
  }
 ]
}